apiVersion: v1
kind: Service
metadata:
  name: chack-events-service
spec:
  selector:
    app: chack-events-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: web
